### ISSUE TITLE
Derive Mnemonic Phrase from Seed?

### ISSUE THREAD

**Issue by woodser** [iancoleman/jsbip39#2]
Hi, thanks for your work on this.  It's built well.

I'm wondering if there is a way to recover the mnemonic phrase from a hexadecimal string.  Specifically, jsbip39.js:131 self.toSeed() generates a hexadecimal string.  Is it possible to convert that back to the original mnemonic phrase?

Thanks!

**Comment by woodser** [comment]
Nice, I see that you are working on a [BIP39 tool with Shamir's Secret Sharing](https://iancoleman.io/shamir39/).  That is exactly what I'm intending to add [cryptostorage.com](https://cryptostorage.com).  I'll check out your code.  This is great work.

**Comment by iancoleman** [comment]
> I'm wondering if there is a way to recover the mnemonic phrase from a hexadecimal string

No, since the mnemonic is PBKDF2 (ie hashed) to get the seed. That hash cannot be reversed back into entropy / mnemonic.

If you like Shamir39 I recommend checking out [SLIP-0039- Shamir's Secret-Sharing for Mnemonic Codes](https://github.com/satoshilabs/slips/blob/master/slip-0039.md).

**Comment by woodser** [comment]
@iancoleman,

I have a [branch of my tool](https://github.com/cryptostorage/cryptostorage.com/tree/bip39) which supports BIP39 mnemonic phrase generation, passphrase-protection, and splitting using Shamir's Secret Sharing and code from your repository.

It's using code from shamir39.js to convert between BIP39 mnemonic phrases and hexadecimals.  The hexadecimal is used as input to Shamir's.  I factored out two methods, [Shamir39.getHexFromWords()](https://github.com/cryptostorage/cryptostorage.com/blob/bip39/lib/bip39.js#L410) and [Shamir39.getWordsFromHex()](https://github.com/cryptostorage/cryptostorage.com/blob/bip39/lib/bip39.js#L443) specifically for this purpose.  I think these methods are useful as standalone utilities.

The splitting feature is not currently using the [draft specification](https://github.com/satoshilabs/slips/blob/master/slip-0039.md) for splitting BIP39 mnemonic phrases.

If you have feedback before I make this generally available, it's especially welcome and appreciated.  Thanks.
